# Dockerfile.mysql
FROM mysql:8.4

# Use microdnf instead of apt-get (since base image is Oracle Linux)
RUN microdnf install -y glibc-locale-source glibc-langpack-ja \
    && localedef -f UTF-8 -i ja_JP ja_JP.UTF-8 \
    && microdnf clean all

ENV LANG=ja_JP.UTF-8 \
    LANGUAGE=ja_JP:ja \
    LC_ALL=ja_JP.UTF-8

CMD ["mysqld"]
